### ISSUE TITLE
Add a new shortcut to move backwards in the reminder list

### ISSUE THREAD

**Issue by Aban** [giovannyreyeso/code-reminder#1]
Hello Sir giovannyreyeso,

My team and me would love to have a shortcut to move backwards in the reminder list. We think that a good shortcut for this could be **ctrl + c** in OS X.

Thanks for all your hard work.
Regards

**Comment by giovannyreyeso** [comment]
What great idea!!, thanks!!. i will work hard for do it!

Coming soon!

**Comment by giovannyreyeso** [comment]
Done!, soon you will are receiving the update. ready on v0.0.4!
